;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning-of-line
        coffee-dedent-line-backspace
        cua-cut-region
        cua-paste
        eval-and-replace
        eval-last-sexp
        evil-backward-char
        evil-delete
        evil-forward-char
        evil-yank
        ido-switch-buffer
        indent-for-tab-command
        isearch-abort
        isearch-backward-regexp
        isearch-delete-char
        isearch-printing-char
        org-end-of-line
        org-force-self-insert
        org-self-insert-command
        undo-tree-visualize
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        cua-copy-region
        cua-delete-region
        cua-set-rectangle-mark
        describe-key
        electric-indent-just-newline
        end-of-buffer
        isearch-forward-regexp
        kill-region
        mouse-set-region
        ruby-interpolate
        smex
        tab-to-tab-stop
        yaml-electric-backspace
        ))
